drm: xylon: compiling error
This patch is to fix the compiling errors due to the different base
of xylon DRM between the current kernel and SDK git repo, orthewise
the following errors will be popped out:

drivers/gpu/drm/xylon/xylon_fb.c: In function 'xylon_drm_fb_destroy':
drivers/gpu/drm/xylon/xylon_fb.c:41:3: error: implicit declaration of function 'drm_gem_object_unreference_unlocked' [-Werror=implicit-function-declaration]
   drm_gem_object_unreference_unlocked(obj);
   ^
drivers/gpu/drm/xylon/xylon_fb.c: In function 'xylon_drm_fb_create_handle':
drivers/gpu/drm/xylon/xylon_fb.c:52:2: error: implicit declaration of function 'drm_gem_handle_create' [-Werror=implicit-function-declaration]
  return drm_gem_handle_create(file_priv, xfb->obj, handle);
  ^
drivers/gpu/drm/xylon/xylon_fb.c: In function 'xylon_drm_fb_create':
drivers/gpu/drm/xylon/xylon_fb.c:116:2: error: implicit declaration of function 'drm_gem_object_lookup' [-Werror=implicit-function-declaration]
  obj = drm_gem_object_lookup(dev, file_priv, mode_cmd->handles[0]);
  ^
drivers/gpu/drm/xylon/xylon_fb.c:116:6: warning: assignment makes pointer from integer without a cast
  obj = drm_gem_object_lookup(dev, file_priv, mode_cmd->handles[0]);
      ^
drivers/gpu/drm/xylon/xylon_drv.c: In function 'xylon_drm_platform_remove':
drivers/gpu/drm/xylon/xylon_drv.c:315:2: error: implicit declaration of function 'drm_platform_exit' [-Werror=implicit-function-declaration]
  drm_platform_exit(&xylon_drm_driver, pdev);
  ^

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>