mfd: intel_vuport: use back property_set struct
Fix for this compilation error,

drivers/mfd/intel-vuport.c:38:3:
error: unknown field ‘properties’ specified in initializer
   .properties = reg_properties,

due to missing commit f4d052660323 ("device property: don't bother the
drivers with struct property_set") from mainline.

Signed-off-by: Wan Ahmad Zainie <wan.ahmad.zainie.wan.mohamad@intel.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>