dpaa_eth: fix device attribute mode error
Kernel introduce macro "VERIFY_OCTAL_PERMISSIONS" to check the
mode value in "struct device_attribute", and 0x644 is wrong value
which exceed 0777, so use macro S_IRUGO instead, or it will occur
build error as below:

include/linux/bug.h:33:45: error: negati
ve width in bit-field '<anonymous>'
 #define BUILD_BUG_ON_ZERO(e) (sizeof(struct { int:-!!(e); }))
                                             ^
include/linux/kernel.h:823:3: note: in e
xpansion of macro 'BUILD_BUG_ON_ZERO'
   BUILD_BUG_ON_ZERO((perms) > 0777) +    \
   ^
include/linux/sysfs.h:92:12: note: in ex
pansion of macro 'VERIFY_OCTAL_PERMISSIONS'
    .mode = VERIFY_OCTAL_PERMISSIONS(_mode) },  \
            ^
include/linux/device.h:541:45: note: in
expansion of macro '__ATTR'
  struct device_attribute dev_attr_##_name = __ATTR(_name, _mode, _show, _store)

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>