crypto: caam - Add define for NULL encryption
This define is required for making descriptors
with NULL encryption.

drivers/staging/fsl_dpa_offload/dpa_ipsec.c:45:355: error: ‘OP_PCL_IPSEC_NULL_ENC’ undeclared here (not in a function)
  struct ipsec_alg_suite ipsec_algs[] = IPSEC_ALGS;
drivers/staging/fsl_dpa_offload/dpa_ipsec.c: In function ‘check_sa_params’:
drivers/staging/fsl_dpa_offload/dpa_ipsec.c:2991:17: warning: comparison between pointer and integer [enabled by default]
  if (cipher_alg != OP_PCL_IPSEC_NULL_ENC &&
                 ^

Dropped during: b7c81aa Merge remote-tracking branch 'linus/master' into merge

Signed-off-by: Andrei Varvara <andrei.varvara@freescale.com>
Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: I61ef1a7d6bcf115f99f5160f76154c09e5f7f7da
Reviewed-on: http://git.am.freescale.net:8181/7991
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
[Kevin: Original patch taken from fsl QorIQ SDK v1.8 SOURCE yocto.iso]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>