fsl_dce: Include missing OF header files
[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

drivers/staging/fsl_dce/dce_driver.c: In function ‘fsl_dce_probe’:
drivers/staging/fsl_dce/dce_driver.c:154:2: error: implicit declaration of function ‘of_iomap’ [-Werror=implicit-function-declaration]
  topregs = of_iomap(nprop, 0);
  ^
drivers/staging/fsl_dce/dce_driver.c:164:2: error: implicit declaration of function ‘of_irq_to_resource’ [-Werror=implicit-function-declaration]
  ctrlpriv->err_irq = of_irq_to_resource(nprop, 0, NULL);
		    ^
drivers/staging/fsl_dce/dce_driver.c:164:2: error: implicit declaration of function ‘of_irq_to_resource’ [-Werror=implicit-function-declaration]
  ctrlpriv->err_irq = of_irq_to_resource(nprop, 0, NULL);
  ^
drivers/staging/fsl_dce/dce_debugfs.c: In function ‘init_ccsrmempeek’:
drivers/staging/fsl_dce/dce_debugfs.c:77:2: error: implicit declaration of function ‘of_get_address’ [-Werror=implicit-function-declaration]
  regaddr_p = of_get_address(dn, 0, &dce_ccsr_size, NULL);
  ^
drivers/staging/fsl_dce/dce_debugfs.c:82:2: error: implicit declaration of function ‘of_translate_address’ [-Werror=implicit-function-declaration]
  dce_ccsr_start = of_translate_address(dn, regaddr_p);
  ^

Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: Ia8f4acb61349ae8a5edb87f5767784b328993d46
Reviewed-on: http://git.am.freescale.net:8181/7721
Reviewed-by: Haiying Wang <Haiying.Wang@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
Tested-by: Emilian Medve <Emilian.Medve@freescale.com>