fsl_eth: replace __get_cpu_var with this_cpu_ptr in module qman-test
According to the upstream commit 69111bac42f5
("powerpc: Replace __get_cpu_var uses"), use this_cpu_ptr
instead of __get_cpu_var, or else we will get a compile error
as below:

drivers/staging/fsl_qbman/qman_test_hotpotato.c:276:27: error: implicit declaration of function '__get_cpu_var' [-Werror=implicit-function-declaration]
  struct hp_cpu *hp_cpu = &__get_cpu_var(hp_cpus);
                           ^
drivers/staging/fsl_qbman/qman_test_hotpotato.c:276:26: error: lvalue required as unary '&' operand
  struct hp_cpu *hp_cpu = &__get_cpu_var(hp_cpus);

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>