iommu/fsl: fix compile error
This is a part of commit 93f1de0be908. Fix a compile error as below:

drivers/iommu/fsl_pamu.c:1382:3: error: too few arguments to function 'setup_one_pamu'
 setup_one_pamu(pamu_reg_base, ppaact_phys, spaact_phys,
 ^

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>