mmc: esdhc: move platform_reset_enter/exit to esdhc_reset
According to upstream commit 03231f9b781f
("mmc: sdhci: convert reset into a library function"),
the function platform_reset_enter/exit has been removed from sdhci_ops.
So move esdhc's platform_reset_enter/exit to esdhc_reset to guanrantee
the correct reset order. Or it will occur a compile error as below:

drivers/mmc/host/sdhci-of-esdhc.c:553:2
 error: unknown field 'platform_reset_enter' specified in initializer
  .platform_reset_enter = esdhc_of_platform_reset_enter,
  ^
drivers/mmc/host/sdhci-of-esdhc.c:553:26
: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .platform_reset_enter = esdhc_of_platform_reset_enter,
                          ^
drivers/mmc/host/sdhci-of-esdhc.c:553:26: note: (near initialization for 'sdhci_esdhc_ops.adma_workaround')
drivers/mmc/host/sdhci-of-esdhc.c:554:2  error: unknown field 'platform_reset_exit' specified in initializer
  .platform_reset_exit = esdhc_of_platform_reset_exit,
  ^
drivers/mmc/host/sdhci-of-esdhc.c:554:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .platform_reset_exit = esdhc_of_platform_reset_exit,
                         ^
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>