drm: xylon: Fix runtime PM support in the driver
This patch comes from:
  https://github.com/Xilinx/linux-xlnx.git

Error reported by Kbuild:
   In file included from include/linux/device.h:25:0,
                    from include/linux/dma-mapping.h:5,
                    from include/drm/drmP.h:37,
                    from drivers/gpu/drm/xylon/xylon_drv.c:20:
>> drivers/gpu/drm/xylon/xylon_drv.c:305:21: error:
>> 'xylon_drm_pm_suspend' undeclared here (not in a function)
     SET_RUNTIME_PM_OPS(xylon_drm_pm_suspend, xylon_drm_pm_resume, NULL)
   include/linux/pm.h:347:21: note: in definition of macro
'SET_RUNTIME_PM_OPS'
     .runtime_suspend = suspend_fn, \
>> drivers/gpu/drm/xylon/xylon_drv.c:305:43: error:
>> 'xylon_drm_pm_resume' undeclared here (not in a function)
     SET_RUNTIME_PM_OPS(xylon_drm_pm_suspend, xylon_drm_pm_resume, NULL)
   include/linux/pm.h:348:20: note: in definition of macro
'SET_RUNTIME_PM_OPS'
     .runtime_resume = resume_fn, \

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit 34463a36fdbaf49d447a42c4bb34b27c8e829c0f)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>