iommu: fsl-t2xxx: add variable declaration for compiling error
Because of upstream commit 70ebd071ea1a
("iommu/fsl: Really fix init section(s) content"), the global variable
"struct ome *omt" has been change to a local variable in fsl_pamu_probe.
So we need to add variable decalaration for "omt" in iommu_resume, or it
will occurr compiling error as below:

drivers/iommu/fsl_pamu.c:1479:24: error: 'omt' undeclared (first use in this function)
           virt_to_phys(omt));
                        ^
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>